# Generated by Django 2.0.1 on 2018-05-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
